-- This is everything used to build up the table for testing
-- create table Houses(id serial primary key, name text, address text, city text, state text, zipcode text)
--ALTER TABLE houses
-- ADD COLUMN Image varchar,
-- Add COLUMN Monthly_Mortgage VARCHAR,
-- ADD COLUMN Amount VARCHAR,
-- ADD COLUMN Desired_Rent VARCHAR;
